SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory4> .  ?v0 <http://ogp.me/ns#tag> ?v1 .  ?v0 <http://schema.org/contentRating> ?v5 .  ?v0 <http://schema.org/contentSize> ?v6 .  ?v0 <http://schema.org/description> ?v7 .  ?v8 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .  ?v2 <http://ogp.me/ns#tag> ?v1 .  ?v2 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v4 .  }
