# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sage_response.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sage_response.proto',
  package='sageresponse',
  syntax='proto3',
  serialized_pb=_b('\n\x13sage_response.proto\x12\x0csageresponse\"C\n\rTriplePattern\x12\x0f\n\x07subject\x18\x01 \x01(\t\x12\x11\n\tpredicate\x18\x02 \x01(\t\x12\x0e\n\x06object\x18\x03 \x01(\t\"*\n\x07\x42inding\x12\x10\n\x08variable\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"5\n\nBindingBag\x12\'\n\x08\x62indings\x18\x01 \x03(\x0b\x32\x15.sageresponse.Binding\"8\n\x0eSageStatistics\x12\x12\n\nexportTime\x18\x01 \x01(\x01\x12\x12\n\nimportTime\x18\x02 \x01(\x01\"\x86\x01\n\x0cSageResponse\x12*\n\x08\x62indings\x18\x01 \x03(\x0b\x32\x18.sageresponse.BindingBag\x12\x0c\n\x04next\x18\x02 \x01(\t\x12\x0f\n\x07hasNext\x18\x03 \x01(\x08\x12+\n\x05stats\x18\x04 \x01(\x0b\x32\x1c.sageresponse.SageStatisticsb\x06proto3')
)




_TRIPLEPATTERN = _descriptor.Descriptor(
  name='TriplePattern',
  full_name='sageresponse.TriplePattern',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='subject', full_name='sageresponse.TriplePattern.subject', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='predicate', full_name='sageresponse.TriplePattern.predicate', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='object', full_name='sageresponse.TriplePattern.object', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=104,
)


_BINDING = _descriptor.Descriptor(
  name='Binding',
  full_name='sageresponse.Binding',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='variable', full_name='sageresponse.Binding.variable', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='sageresponse.Binding.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=148,
)


_BINDINGBAG = _descriptor.Descriptor(
  name='BindingBag',
  full_name='sageresponse.BindingBag',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bindings', full_name='sageresponse.BindingBag.bindings', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=203,
)


_SAGESTATISTICS = _descriptor.Descriptor(
  name='SageStatistics',
  full_name='sageresponse.SageStatistics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='exportTime', full_name='sageresponse.SageStatistics.exportTime', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='importTime', full_name='sageresponse.SageStatistics.importTime', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=205,
  serialized_end=261,
)


_SAGERESPONSE = _descriptor.Descriptor(
  name='SageResponse',
  full_name='sageresponse.SageResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bindings', full_name='sageresponse.SageResponse.bindings', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='next', full_name='sageresponse.SageResponse.next', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hasNext', full_name='sageresponse.SageResponse.hasNext', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stats', full_name='sageresponse.SageResponse.stats', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=264,
  serialized_end=398,
)

_BINDINGBAG.fields_by_name['bindings'].message_type = _BINDING
_SAGERESPONSE.fields_by_name['bindings'].message_type = _BINDINGBAG
_SAGERESPONSE.fields_by_name['stats'].message_type = _SAGESTATISTICS
DESCRIPTOR.message_types_by_name['TriplePattern'] = _TRIPLEPATTERN
DESCRIPTOR.message_types_by_name['Binding'] = _BINDING
DESCRIPTOR.message_types_by_name['BindingBag'] = _BINDINGBAG
DESCRIPTOR.message_types_by_name['SageStatistics'] = _SAGESTATISTICS
DESCRIPTOR.message_types_by_name['SageResponse'] = _SAGERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TriplePattern = _reflection.GeneratedProtocolMessageType('TriplePattern', (_message.Message,), dict(
  DESCRIPTOR = _TRIPLEPATTERN,
  __module__ = 'sage_response_pb2'
  # @@protoc_insertion_point(class_scope:sageresponse.TriplePattern)
  ))
_sym_db.RegisterMessage(TriplePattern)

Binding = _reflection.GeneratedProtocolMessageType('Binding', (_message.Message,), dict(
  DESCRIPTOR = _BINDING,
  __module__ = 'sage_response_pb2'
  # @@protoc_insertion_point(class_scope:sageresponse.Binding)
  ))
_sym_db.RegisterMessage(Binding)

BindingBag = _reflection.GeneratedProtocolMessageType('BindingBag', (_message.Message,), dict(
  DESCRIPTOR = _BINDINGBAG,
  __module__ = 'sage_response_pb2'
  # @@protoc_insertion_point(class_scope:sageresponse.BindingBag)
  ))
_sym_db.RegisterMessage(BindingBag)

SageStatistics = _reflection.GeneratedProtocolMessageType('SageStatistics', (_message.Message,), dict(
  DESCRIPTOR = _SAGESTATISTICS,
  __module__ = 'sage_response_pb2'
  # @@protoc_insertion_point(class_scope:sageresponse.SageStatistics)
  ))
_sym_db.RegisterMessage(SageStatistics)

SageResponse = _reflection.GeneratedProtocolMessageType('SageResponse', (_message.Message,), dict(
  DESCRIPTOR = _SAGERESPONSE,
  __module__ = 'sage_response_pb2'
  # @@protoc_insertion_point(class_scope:sageresponse.SageResponse)
  ))
_sym_db.RegisterMessage(SageResponse)


# @@protoc_insertion_point(module_scope)
