swagger: "2.0"
info:
  description: "Documentation for the SaGe API"
  version: "1.0.0"
  title: "SaGe API"
  contact:
    email: "sage@univ-nantes.fr"
  license:
    name: "MIT"
    url: "https://github.com/sage-org/sage-engine/blob/master/LICENSE"
basePath: "/"
tags:
- name: "sparql"
  description: "Evaluate SPARQL queries using the SaGe preemptive SPARQL query server"
  externalDocs:
    description: "See more"
    url: "http://sage.univ-nantes.fr/"
- name: "void"
  description: "Get VoID descriptions"
  externalDocs:
    description: "See more"
    url: "https://www.w3.org/TR/void/"
- name: "miscellaneous"
  description: "Miscellaneous operations"
schemes:
- "http"
paths:
  /sparql/{dataset}:
    post:
      tags:
      - "sparql"
      summary: "Execute a SPARQL query"
      description: "Execute a SPARQL query using the preemptive SPARQL query server"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      - "application/sparql-results+json"
      - "application/sparql-results+xml"
      parameters:
      - name: "dataset"
        in: "path"
        description: "Name of the RDF dataset queried"
        required: true
        type: "string"
      - in: "body"
        name: "query"
        description: "Query object"
        required: true
        schema:
          $ref: "#/definitions/QueryObject"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/QueryResponse"
        500:
          description: "Invalid query"
  /void/:
    get:
      tags:
      - "void"
      summary: "Get the Server VoID description"
      description: "Get the VoID description of the SaGe server"
      produces:
      - "application/xml"
      - "application/n-triples"
      - "application/json"
      - "text/turtle"
      responses:
        200:
          description: "Successful operation"
        500:
          description: "Invalid query"
  /void/{dataset}:
    get:
      tags:
      - "void"
      summary: "Get VoID description of a RDF Dataset"
      description: "Get the VoID description of a RDF Dataset hosted by the SaGe server"
      produces:
      - "application/xml"
      - "application/n-triples"
      - "application/json"
      - "text/turtle"
      parameters:
      - name: "dataset"
        in: "path"
        description: "Name of the RDF dataset"
        required: true
        type: "string"
      responses:
        200:
          description: "Successful operation"
        500:
          description: "Invalid query"
  /api/:
    get:
      tags:
      - "miscellaneous"
      summary: "Get the Server OpenAPI specification"
      description: "Get the Server OpenAPI specification"
      produces:
      - "text/yaml"
      responses:
        200:
          description: "Successful operation"
definitions:
  TriplePattern:
    type: "object"
    description: "Triple pattern"
    properties:
      triple:
        type: "string"
        description: "Triple pattern's subject"
        example: "http://example.org#Alice"
      predicate:
        type: "string"
        description: "Triple pattern's predicate"
        example: "http://xmlns.com/foaf/0.1/knows"
      object:
        type: "string"
        description: "Triple pattern's object"
        example: "?bob"
  QueryObject:
    type: "object"
    example:
      - type: "bgp"
        bgp:
          - subject: "http://example.org#Alice"
            predicate: "http://xmlns.com/foaf/0.1/knows"
            object: "?bob"
        filters:
          - "isIRI(?bob) && ?alice != ?bob"
    properties:
      query:
        type: "object"
        description: "Query content"
        properties:
          type:
            type: "string"
            description: "Query type"
            enum: [ "bgp", "union" ]
            example: "bgp"
          bgp:
            type: "array"
            description: "Basic Graph pattern to evaluate"
            items:
              $ref: '#/definitions/TriplePattern'
          filters:
            type: array
            description: "SPARQL Filters to evaluate"
            items:
              type: "string"
              example: "isIRI(?bob) && ?alice != ?bob"
          union:
            type: "array"
            description: "Union of Basic Graph patterns to evaluate"
            items:
              type: "array"
              items:
                $ref: '#/definitions/TriplePattern'
      next:
        type: "string"
        description: "Next link used to resume query execution"
  QueryResponse:
    type: "object"
    example:
      bindings:
        - ?bob: "http://example.org#Sponge_Bob"
        - ?bob: "http://example.org#Bob_Lennon"
      next: "xRVCiMKAj9zCgI=="
      hasNext: true
      pageSize: 2
    properties:
      bindings:
        type: "array"
        description: "Solutions bindings"
        items:
          type: "object"
      next:
        type: "string"
        description: "Next link used to resume query processing"
      hasNext:
        type: "boolean"
      pageSize:
        type: "integer"
        description: "Number of solution bindings in this response"
externalDocs:
  description: "Find out more about SaGe"
  url: "http://sage.univ-nantes.fr"
